import { Product, Review } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Cotton T-Shirt',
    price: 49,
    category: 'men',
    subcategory: 'tops',
    description: 'Premium organic cotton t-shirt with a relaxed fit. Perfect for everyday wear, this piece combines comfort with timeless style.',
    fabric: '100% Organic Cotton',
    images: ['men-tshirt-white', 'men-tshirt-detail'],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Black', hex: '#000000' },
      { name: 'Sand', hex: '#C2B280' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    isBestseller: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: '2',
    name: 'Tailored Wool Blazer',
    price: 299,
    originalPrice: 399,
    category: 'men',
    subcategory: 'outerwear',
    description: 'Sophisticated wool blazer with modern tailoring. Features notch lapels, two-button closure, and functional pockets.',
    fabric: '80% Wool, 20% Polyester',
    images: ['men-blazer-navy', 'men-blazer-side'],
    colors: [
      { name: 'Navy', hex: '#1B2845' },
      { name: 'Charcoal', hex: '#36454F' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.9,
    reviews: 89,
  },
  {
    id: '3',
    name: 'Slim Fit Chinos',
    price: 89,
    category: 'men',
    subcategory: 'bottoms',
    description: 'Classic chinos with a modern slim fit. Made from breathable cotton blend for all-day comfort.',
    fabric: '97% Cotton, 3% Elastane',
    images: ['men-chinos-beige', 'men-chinos-detail'],
    colors: [
      { name: 'Beige', hex: '#F5F5DC' },
      { name: 'Olive', hex: '#6B8E23' },
      { name: 'Navy', hex: '#1B2845' },
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    isBestseller: true,
    rating: 4.7,
    reviews: 203,
  },
  {
    id: '4',
    name: 'Merino Wool Sweater',
    price: 129,
    category: 'men',
    subcategory: 'knitwear',
    description: 'Luxurious merino wool sweater with ribbed crew neck. Temperature-regulating and incredibly soft.',
    fabric: '100% Merino Wool',
    images: ['men-sweater-grey', 'men-sweater-texture'],
    colors: [
      { name: 'Grey', hex: '#808080' },
      { name: 'Camel', hex: '#C19A6B' },
      { name: 'Forest Green', hex: '#228B22' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isNew: true,
    rating: 4.9,
    reviews: 67,
  },
  {
    id: '5',
    name: 'Silk Blend Blouse',
    price: 119,
    category: 'women',
    subcategory: 'tops',
    description: 'Elegant silk blend blouse with relaxed fit. Features delicate mother-of-pearl buttons and flowing sleeves.',
    fabric: '70% Silk, 30% Cotton',
    images: ['women-blouse-ivory', 'women-blouse-detail'],
    colors: [
      { name: 'Ivory', hex: '#FFFFF0' },
      { name: 'Rose', hex: '#FFE4E1' },
      { name: 'Sage', hex: '#9DC183' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isBestseller: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: '6',
    name: 'High-Waist Wide Leg Trousers',
    price: 149,
    category: 'women',
    subcategory: 'bottoms',
    description: 'Sophisticated wide-leg trousers with high waist. Flattering silhouette perfect for both office and evening wear.',
    fabric: '60% Viscose, 35% Polyester, 5% Elastane',
    images: ['women-trousers-black', 'women-trousers-side'],
    colors: [
      { name: 'Black', hex: '#000000' },
      { name: 'Caramel', hex: '#AF6E4D' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviews: 112,
  },
  {
    id: '7',
    name: 'Cashmere Cardigan',
    price: 249,
    category: 'women',
    subcategory: 'knitwear',
    description: 'Pure cashmere cardigan with ribbed edges. Timeless piece that adds luxury to any outfit.',
    fabric: '100% Cashmere',
    images: ['women-cardigan-cream', 'women-cardigan-detail'],
    colors: [
      { name: 'Cream', hex: '#FFFDD0' },
      { name: 'Charcoal', hex: '#36454F' },
      { name: 'Dusty Rose', hex: '#DCAE96' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isNew: true,
    isBestseller: true,
    rating: 5.0,
    reviews: 93,
  },
  {
    id: '8',
    name: 'Linen Midi Dress',
    price: 179,
    category: 'women',
    subcategory: 'dresses',
    description: 'Effortless linen midi dress with adjustable waist tie. Perfect for warm weather with its breathable fabric.',
    fabric: '100% European Linen',
    images: ['women-dress-linen', 'women-dress-back'],
    colors: [
      { name: 'Natural', hex: '#F5F5DC' },
      { name: 'Terracotta', hex: '#E2725B' },
      { name: 'Navy', hex: '#1B2845' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isNew: true,
    rating: 4.6,
    reviews: 78,
  },
  {
    id: '9',
    name: 'Leather Crossbody Bag',
    price: 199,
    category: 'women',
    subcategory: 'accessories',
    description: 'Handcrafted leather crossbody bag with adjustable strap. Compact yet spacious with multiple compartments.',
    fabric: 'Full-Grain Leather',
    images: ['women-bag-leather', 'women-bag-detail'],
    colors: [
      { name: 'Tan', hex: '#D2B48C' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: ['One Size'],
    rating: 4.9,
    reviews: 145,
  },
  {
    id: '10',
    name: 'Classic Oxford Shirt',
    price: 79,
    category: 'men',
    subcategory: 'tops',
    description: 'Traditional oxford shirt with button-down collar. A wardrobe essential that works for any occasion.',
    fabric: '100% Cotton Oxford',
    images: ['men-oxford-white', 'men-oxford-detail'],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Light Blue', hex: '#ADD8E6' },
      { name: 'Pink', hex: '#FFB6C1' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isBestseller: true,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: '11',
    name: 'Denim Jacket',
    price: 139,
    category: 'men',
    subcategory: 'outerwear',
    description: 'Classic denim jacket with modern fit. Versatile piece that adds character to any outfit.',
    fabric: '100% Cotton Denim',
    images: ['men-denim-jacket', 'men-denim-back'],
    colors: [
      { name: 'Indigo', hex: '#4B0082' },
      { name: 'Black', hex: '#000000' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviews: 134,
  },
  {
    id: '12',
    name: 'Wool Overcoat',
    price: 399,
    category: 'men',
    subcategory: 'outerwear',
    description: 'Premium wool overcoat with timeless design. Features notched lapels and double-breasted closure.',
    fabric: '90% Wool, 10% Cashmere',
    images: ['men-overcoat-grey', 'men-overcoat-side'],
    colors: [
      { name: 'Grey', hex: '#808080' },
      { name: 'Navy', hex: '#1B2845' },
      { name: 'Camel', hex: '#C19A6B' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 5.0,
    reviews: 56,
  },
];

export const testimonials = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Fashion Blogger',
    content: 'The quality is outstanding. Every piece I\'ve bought has become a staple in my wardrobe. The attention to detail is remarkable.',
    rating: 5,
    image: 'testimonial-woman',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Creative Director',
    content: 'Finally, a brand that understands modern tailoring. The fit is perfect and the fabrics feel luxurious.',
    rating: 5,
    image: 'testimonial-man',
  },
  {
    id: '3',
    name: 'Emma Williams',
    role: 'Stylist',
    content: 'I recommend this brand to all my clients. Timeless designs that work season after season.',
    rating: 5,
    image: 'testimonial-woman-2',
  },
];

export const reviews: Record<string, Review[]> = {
  '1': [
    {
      id: 'r1',
      author: 'David M.',
      rating: 5,
      date: '2026-01-15',
      comment: 'Best t-shirt I\'ve ever owned. The fabric is incredibly soft and it holds up well after multiple washes.',
    },
    {
      id: 'r2',
      author: 'Alex R.',
      rating: 5,
      date: '2026-01-10',
      comment: 'Perfect fit and amazing quality. Worth every penny.',
    },
    {
      id: 'r3',
      author: 'Chris L.',
      rating: 4,
      date: '2026-01-05',
      comment: 'Great shirt, runs slightly large so consider sizing down.',
    },
  ],
  '7': [
    {
      id: 'r4',
      author: 'Jennifer K.',
      rating: 5,
      date: '2026-01-20',
      comment: 'This cardigan is pure luxury. So soft and warm without being bulky.',
    },
    {
      id: 'r5',
      author: 'Lisa P.',
      rating: 5,
      date: '2026-01-18',
      comment: 'Investment piece that will last forever. Beautiful quality.',
    },
  ],
};
